apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zdpe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zdpe
    app.kubernetes.io/part-of: integ-app-mwtl
  name: hacbs-test-project-zdpe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zdpe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zdpe
    spec:
      containers:
      - image: quay.io/bootstrap/nbe-e2e-pzsg-tenant/integ-app-mwtl/hacbs-test-project-zdpe@sha256:39d926f87af161fe1e1891baf9c06b928a10d0ecebaab6a53acab93e4f68bccf
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
