apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-zdpe
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/bootstrap/nbe-e2e-pzsg-tenant/integ-app-mwtl/hacbs-test-project-zdpe@sha256:39d926f87af161fe1e1891baf9c06b928a10d0ecebaab6a53acab93e4f68bccf
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
